const statusMap = {
  'da verificare': 'warning',
  confermato: 'success',
  incompleto: 'danger',
  'possibile duplicato': 'danger',
  duplicato: 'danger',
  verificato: 'success',
  'in attesa': 'info',
  'da controllare': 'warning',
  scartato: 'muted',
  'da revisionare': 'warning',
  approvata: 'success',
  pubblicata: 'success',
  'non pubblicabile': 'muted',
  'da avviare': 'muted',
  attivo: 'success',
  'in corso': 'info',
  critico: 'danger',
  chiuso: 'success',
  sospeso: 'danger',
  completato: 'success',
  archiviato: 'muted',
  nuovo: 'warning',
  'da valutare': 'warning',
  contattato: 'info',
  'in attesa cliente': 'info',
  accettato: 'success',
  rifiutato: 'danger',
  aperto: 'danger',
  alta: 'danger',
  media: 'warning',
  bassa: 'info',
  system: 'system',
  note: 'note',
  document: 'document',
  documents: 'document',
  photo: 'photo',
  photos: 'photo',
  estimates: 'info',
}

export function getStatusTone(status) {
  return statusMap[String(status).toLowerCase()] ?? 'info'
}
